package com.veldin.stringpipelines.codepoints;

import com.veldin.stringpipelines.ICodePointOperation;
import com.veldin.stringpipelines.codepoints.utils.CodePointUtils;

public enum ECodePointOperation implements ICodePointOperation {

    CAPITALIZE(CodePointUtils::capitalize),
    CHOMP(CodePointUtils::chomp),
    CHOP(CodePointUtils::chop),
    LOWER_CASE(CodePointUtils::lowerCase),
    NORMALIZE_SPACE(CodePointUtils::normalizeSpace),
    REVERSE(CodePointUtils::reverse),
    STRIP(CodePointUtils::strip),

    UNCAPITALIZE(CodePointUtils::uncapitalize),
    TOGGLE_CASE(CodePointUtils::toggleCase),

    ROTATE_LEFT(CodePointUtils::rotateLeft),
    ROTATE_RIGHT(CodePointUtils::rotateRight),
    INCREMENT(CodePointUtils::increment),
    DECREMENT(CodePointUtils::decrement),

    REMOVE_LAST(CodePointUtils::removeLast),
    REMOVE_FIRST(CodePointUtils::removeFirst),

    TO_BASE64(CodePointUtils::toBase64),
    FROM_BASE64(CodePointUtils::fromBase64),

    TO_XML_ENTITIES(CodePointUtils::toXmlEntities),
    FROM_XML_ENTITIES(CodePointUtils::fromXmlEntities),

    // SortCharacters

    // Resize (Set buffer to a specific size, fill it. (Whitespace? Underscore?)

    // emojis to text (aka) 🔥 to :fire: (and back)

    //Keep/Remove htmlEntities / xmlEntities

    // Normalise "'` QuotePunctuation

    // REMOVE_BOM

    // SPLIT PREPENT or /we on https://www.compart.com/en/unicode/U+001F
    // Or should we instead of a unicode character, use _ as a 'replacement' character?

    // Character based filters

    // Same methods using CharacterHelper

    // Character.getType(cp) types

    REMOVE_VALID_CODE_POINTS(CodePointUtils::removeValidCodePoints),
    KEEP_VALID_CODE_POINTS(CodePointUtils::keepValidCodePoints),
    REMOVE_VALID_CODE_POINTS_PREFIX(CodePointUtils::removeValidCodePointsPrefix),
    KEEP_VALID_CODE_POINTS_PREFIX(CodePointUtils::keepValidCodePointsPrefix),
    REMOVE_BMP_CODE_POINTS(CodePointUtils::removeBmpCodePoints),
    KEEP_BMP_CODE_POINTS(CodePointUtils::keepBmpCodePoints),
    REMOVE_BMP_CODE_POINTS_PREFIX(CodePointUtils::removeBmpCodePointsPrefix),
    KEEP_BMP_CODE_POINTS_PREFIX(CodePointUtils::keepBmpCodePointsPrefix),
    REMOVE_SUPPLEMENTARY_CODE_POINTS(CodePointUtils::removeSupplementaryCodePoints),
    KEEP_SUPPLEMENTARY_CODE_POINTS(CodePointUtils::keepSupplementaryCodePoints),
    REMOVE_SUPPLEMENTARY_CODE_POINTS_PREFIX(CodePointUtils::removeSupplementaryCodePointsPrefix),
    KEEP_SUPPLEMENTARY_CODE_POINTS_PREFIX(CodePointUtils::keepSupplementaryCodePointsPrefix),
    REMOVE_LOWER_CASE(CodePointUtils::removeLowerCase),
    KEEP_LOWER_CASE(CodePointUtils::keepLowerCase),
    REMOVE_LOWER_CASE_PREFIX(CodePointUtils::removeLowerCasePrefix),
    KEEP_LOWER_CASE_PREFIX(CodePointUtils::keepLowerCasePrefix),
    REMOVE_UPPER_CASE(CodePointUtils::removeUpperCase),
    KEEP_UPPER_CASE(CodePointUtils::keepUpperCase),
    REMOVE_UPPER_CASE_PREFIX(CodePointUtils::removeUpperCasePrefix),
    KEEP_UPPER_CASE_PREFIX(CodePointUtils::keepUpperCasePrefix),
    REMOVE_TITLE_CASE(CodePointUtils::removeTitleCase),
    KEEP_TITLE_CASE(CodePointUtils::keepTitleCase),
    REMOVE_TITLE_CASE_PREFIX(CodePointUtils::removeTitleCasePrefix),
    KEEP_TITLE_CASE_PREFIX(CodePointUtils::keepTitleCasePrefix),
    REMOVE_DIGITS(CodePointUtils::removeDigits),
    KEEP_DIGITS(CodePointUtils::keepDigits),
    REMOVE_DIGITS_PREFIX(CodePointUtils::removeDigitsPrefix),
    KEEP_DIGITS_PREFIX(CodePointUtils::keepDigitsPrefix),
    REMOVE_DEFINED(CodePointUtils::removeDefined),
    KEEP_DEFINED(CodePointUtils::keepDefined),
    REMOVE_DEFINED_PREFIX(CodePointUtils::removeDefinedPrefix),
    KEEP_DEFINED_PREFIX(CodePointUtils::keepDefinedPrefix),
    REMOVE_LETTERS(CodePointUtils::removeLetters),
    KEEP_LETTERS(CodePointUtils::keepLetters),
    REMOVE_LETTERS_PREFIX(CodePointUtils::removeLettersPrefix),
    KEEP_LETTERS_PREFIX(CodePointUtils::keepLettersPrefix),
    REMOVE_LETTER_OR_DIGITS(CodePointUtils::removeLetterOrDigits),
    KEEP_LETTER_OR_DIGITS(CodePointUtils::keepLetterOrDigits),
    REMOVE_LETTER_OR_DIGITS_PREFIX(CodePointUtils::removeLetterOrDigitsPrefix),
    KEEP_LETTER_OR_DIGITS_PREFIX(CodePointUtils::keepLetterOrDigitsPrefix),
    REMOVE_ALPHABETIC(CodePointUtils::removeAlphabetic),
    KEEP_ALPHABETIC(CodePointUtils::keepAlphabetic),
    REMOVE_ALPHABETIC_PREFIX(CodePointUtils::removeAlphabeticPrefix),
    KEEP_ALPHABETIC_PREFIX(CodePointUtils::keepAlphabeticPrefix),
    REMOVE_IDEOGRAPHICS(CodePointUtils::removeIdeographics),
    KEEP_IDEOGRAPHICS(CodePointUtils::keepIdeographics),
    REMOVE_IDEOGRAPHICS_PREFIX(CodePointUtils::removeIdeographicsPrefix),
    KEEP_IDEOGRAPHICS_PREFIX(CodePointUtils::keepIdeographicsPrefix),
    REMOVE_JAVA_IDENTIFIER_START(CodePointUtils::removeJavaIdentifierStart),
    KEEP_JAVA_IDENTIFIER_START(CodePointUtils::keepJavaIdentifierStart),
    REMOVE_JAVA_IDENTIFIER_START_PREFIX(CodePointUtils::removeJavaIdentifierStartPrefix),
    KEEP_JAVA_IDENTIFIER_START_PREFIX(CodePointUtils::keepJavaIdentifierStartPrefix),
    REMOVE_UNICODE_IDENTIFIER_START(CodePointUtils::removeUnicodeIdentifierStart),
    KEEP_UNICODE_IDENTIFIER_START(CodePointUtils::keepUnicodeIdentifierStart),
    REMOVE_UNICODE_IDENTIFIER_START_PREFIX(CodePointUtils::removeUnicodeIdentifierStartPrefix),
    KEEP_UNICODE_IDENTIFIER_START_PREFIX(CodePointUtils::keepUnicodeIdentifierStartPrefix),
    REMOVE_IDENTIFIER_IGNORABLE(CodePointUtils::removeIdentifierIgnorable),
    KEEP_IDENTIFIER_IGNORABLE(CodePointUtils::keepIdentifierIgnorable),
    REMOVE_IDENTIFIER_IGNORABLE_PREFIX(CodePointUtils::removeIdentifierIgnorablePrefix),
    KEEP_IDENTIFIER_IGNORABLE_PREFIX(CodePointUtils::keepIdentifierIgnorablePrefix),
    REMOVE_EMOJIS(CodePointUtils::removeEmojis),
    KEEP_EMOJIS(CodePointUtils::keepEmojis),
    REMOVE_EMOJIS_PREFIX(CodePointUtils::removeEmojisPrefix),
    KEEP_EMOJIS_PREFIX(CodePointUtils::keepEmojisPrefix),
    REMOVE_EMOJI_PRESENTATION(CodePointUtils::removeEmojiPresentation),
    KEEP_EMOJI_PRESENTATION(CodePointUtils::keepEmojiPresentation),
    REMOVE_EMOJI_PRESENTATION_PREFIX(CodePointUtils::removeEmojiPresentationPrefix),
    KEEP_EMOJI_PRESENTATION_PREFIX(CodePointUtils::keepEmojiPresentationPrefix),
    REMOVE_EMOJI_MODIFIERS(CodePointUtils::removeEmojiModifiers),
    KEEP_EMOJI_MODIFIERS(CodePointUtils::keepEmojiModifiers),
    REMOVE_EMOJI_MODIFIERS_PREFIX(CodePointUtils::removeEmojiModifiersPrefix),
    KEEP_EMOJI_MODIFIERS_PREFIX(CodePointUtils::keepEmojiModifiersPrefix),
    REMOVE_EMOJI_MODIFIER_BASE(CodePointUtils::removeEmojiModifierBase),
    KEEP_EMOJI_MODIFIER_BASE(CodePointUtils::keepEmojiModifierBase),
    REMOVE_EMOJI_MODIFIER_BASE_PREFIX(CodePointUtils::removeEmojiModifierBasePrefix),
    KEEP_EMOJI_MODIFIER_BASE_PREFIX(CodePointUtils::keepEmojiModifierBasePrefix),
    REMOVE_EMOJI_COMPONENTS(CodePointUtils::removeEmojiComponents),
    KEEP_EMOJI_COMPONENTS(CodePointUtils::keepEmojiComponents),
    REMOVE_EMOJI_COMPONENTS_PREFIX(CodePointUtils::removeEmojiComponentsPrefix),
    KEEP_EMOJI_COMPONENTS_PREFIX(CodePointUtils::keepEmojiComponentsPrefix),
    REMOVE_EXTENDED_PICTOGRAPHIC(CodePointUtils::removeExtendedPictographic),
    KEEP_EXTENDED_PICTOGRAPHIC(CodePointUtils::keepExtendedPictographic),
    REMOVE_EXTENDED_PICTOGRAPHIC_PREFIX(CodePointUtils::removeExtendedPictographicPrefix),
    KEEP_EXTENDED_PICTOGRAPHIC_PREFIX(CodePointUtils::keepExtendedPictographicPrefix),
    REMOVE_WHITESPACE(CodePointUtils::removeWhitespace),
    KEEP_WHITESPACE(CodePointUtils::keepWhitespace),
    REMOVE_WHITESPACE_PREFIX(CodePointUtils::removeWhitespacePrefix),
    KEEP_WHITESPACE_PREFIX(CodePointUtils::keepWhitespacePrefix),
    REMOVE_SPACE_CHARS(CodePointUtils::removeSpaceChars),
    KEEP_SPACE_CHARS(CodePointUtils::keepSpaceChars),
    REMOVE_SPACE_CHARS_PREFIX(CodePointUtils::removeSpaceCharsPrefix),
    KEEP_SPACE_CHARS_PREFIX(CodePointUtils::keepSpaceCharsPrefix),
    REMOVE_ISO_CONTROLS(CodePointUtils::removeISOControls),
    KEEP_ISO_CONTROLS(CodePointUtils::keepISOControls),
    REMOVE_ISO_CONTROLS_PREFIX(CodePointUtils::removeISOControlsPrefix),
    KEEP_ISO_CONTROLS_PREFIX(CodePointUtils::keepISOControlsPrefix),
    REMOVE_MIRRORED(CodePointUtils::removeMirrored),
    KEEP_MIRRORED(CodePointUtils::keepMirrored),
    REMOVE_MIRRORED_PREFIX(CodePointUtils::removeMirroredPrefix),
    KEEP_MIRRORED_PREFIX(CodePointUtils::keepMirroredPrefix),

    REMOVE_ASCII_LETTERS(CodePointUtils::removeAsciiLetters),
    KEEP_ASCII_LETTERS(CodePointUtils::keepAsciiLetters),
    REMOVE_ASCII_LETTERS_PREFIX(CodePointUtils::removeAsciiLettersPrefix),
    KEEP_ASCII_LETTERS_PREFIX(CodePointUtils::keepAsciiLettersPrefix),
    REMOVE_ASCII_UPPER_CASE_LETTERS(CodePointUtils::removeAsciiUpperCaseLetters),
    KEEP_ASCII_UPPER_CASE_LETTERS(CodePointUtils::keepAsciiUpperCaseLetters),
    REMOVE_ASCII_UPPER_CASE_LETTERS_PREFIX(CodePointUtils::removeAsciiUpperCaseLettersPrefix),
    KEEP_ASCII_UPPER_CASE_LETTERS_PREFIX(CodePointUtils::keepAsciiUpperCaseLettersPrefix),
    REMOVE_ASCII_LOWER_CASE_LETTERS(CodePointUtils::removeAsciiLowerCaseLetters),
    KEEP_ASCII_LOWER_CASE_LETTERS(CodePointUtils::keepAsciiLowerCaseLetters),
    REMOVE_ASCII_LOWER_CASE_LETTERS_PREFIX(CodePointUtils::removeAsciiLowerCaseLettersPrefix),
    KEEP_ASCII_LOWER_CASE_LETTERS_PREFIX(CodePointUtils::keepAsciiLowerCaseLettersPrefix),
    REMOVE_ASCII_DIGITS(CodePointUtils::removeAsciiDigits),
    KEEP_ASCII_DIGITS(CodePointUtils::keepAsciiDigits),
    REMOVE_ASCII_DIGITS_PREFIX(CodePointUtils::removeAsciiDigitsPrefix),
    KEEP_ASCII_DIGITS_PREFIX(CodePointUtils::keepAsciiDigitsPrefix),
    REMOVE_ASCII_ALPHANUMERIC(CodePointUtils::removeAsciiAlphanumeric),
    KEEP_ASCII_ALPHANUMERIC(CodePointUtils::keepAsciiAlphanumeric),
    REMOVE_ASCII_ALPHANUMERIC_PREFIX(CodePointUtils::removeAsciiAlphanumericPrefix),
    KEEP_ASCII_ALPHANUMERIC_PREFIX(CodePointUtils::keepAsciiAlphanumericPrefix),
    REMOVE_HEX_DIGITS(CodePointUtils::removeHexDigits),
    KEEP_HEX_DIGITS(CodePointUtils::keepHexDigits),
    REMOVE_HEX_DIGITS_PREFIX(CodePointUtils::removeHexDigitsPrefix),
    KEEP_HEX_DIGITS_PREFIX(CodePointUtils::keepHexDigitsPrefix),
    REMOVE_UUID_CHARACTERS(CodePointUtils::removeUuidCharacters),
    KEEP_UUID_CHARACTERS(CodePointUtils::keepUuidCharacters),
    REMOVE_UUID_CHARACTERS_PREFIX(CodePointUtils::removeUuidCharactersPrefix),
    KEEP_UUID_CHARACTERS_PREFIX(CodePointUtils::keepUuidCharactersPrefix),
    REMOVE_BINARY_DIGITS(CodePointUtils::removeBinaryDigits),
    KEEP_BINARY_DIGITS(CodePointUtils::keepBinaryDigits),
    REMOVE_BINARY_DIGITS_PREFIX(CodePointUtils::removeBinaryDigitsPrefix),
    KEEP_BINARY_DIGITS_PREFIX(CodePointUtils::keepBinaryDigitsPrefix),
    REMOVE_OCTAL_DIGITS(CodePointUtils::removeOctalDigits),
    KEEP_OCTAL_DIGITS(CodePointUtils::keepOctalDigits),
    REMOVE_OCTAL_DIGITS_PREFIX(CodePointUtils::removeOctalDigitsPrefix),
    KEEP_OCTAL_DIGITS_PREFIX(CodePointUtils::keepOctalDigitsPrefix),
    REMOVE_BASE64_CHARACTERS(CodePointUtils::removeBase64Characters),
    KEEP_BASE64_CHARACTERS(CodePointUtils::keepBase64Characters),
    REMOVE_BASE64_CHARACTERS_PREFIX(CodePointUtils::removeBase64CharactersPrefix),
    KEEP_BASE64_CHARACTERS_PREFIX(CodePointUtils::keepBase64CharactersPrefix),
    REMOVE_BASE64_URL_CHARACTERS(CodePointUtils::removeBase64UrlCharacters),
    KEEP_BASE64_URL_CHARACTERS(CodePointUtils::keepBase64UrlCharacters),
    REMOVE_BASE64_URL_CHARACTERS_PREFIX(CodePointUtils::removeBase64UrlCharactersPrefix),
    KEEP_BASE64_URL_CHARACTERS_PREFIX(CodePointUtils::keepBase64UrlCharactersPrefix),
    REMOVE_ASCII_WHITESPACES(CodePointUtils::removeAsciiWhitespaces),
    KEEP_ASCII_WHITESPACES(CodePointUtils::keepAsciiWhitespaces),
    REMOVE_ASCII_WHITESPACES_PREFIX(CodePointUtils::removeAsciiWhitespacesPrefix),
    KEEP_ASCII_WHITESPACES_PREFIX(CodePointUtils::keepAsciiWhitespacesPrefix),
    REMOVE_ASCII_PRINTABLE(CodePointUtils::removeAsciiPrintable),
    KEEP_ASCII_PRINTABLE(CodePointUtils::keepAsciiPrintable),
    REMOVE_ASCII_PRINTABLE_PREFIX(CodePointUtils::removeAsciiPrintablePrefix),
    KEEP_ASCII_PRINTABLE_PREFIX(CodePointUtils::keepAsciiPrintablePrefix),
    REMOVE_ASCII_CONTROL(CodePointUtils::removeAsciiControl),
    KEEP_ASCII_CONTROL(CodePointUtils::keepAsciiControl),
    REMOVE_ASCII_CONTROL_PREFIX(CodePointUtils::removeAsciiControlPrefix),
    KEEP_ASCII_CONTROL_PREFIX(CodePointUtils::keepAsciiControlPrefix),
    REMOVE_TITLECASE_LETTERS(CodePointUtils::removeTitlecaseLetters),
    KEEP_TITLECASE_LETTERS(CodePointUtils::keepTitlecaseLetters),
    REMOVE_TITLECASE_LETTERS_PREFIX(CodePointUtils::removeTitlecaseLettersPrefix),
    KEEP_TITLECASE_LETTERS_PREFIX(CodePointUtils::keepTitlecaseLettersPrefix),
    REMOVE_MODIFIER_LETTERS(CodePointUtils::removeModifierLetters),
    KEEP_MODIFIER_LETTERS(CodePointUtils::keepModifierLetters),
    REMOVE_MODIFIER_LETTERS_PREFIX(CodePointUtils::removeModifierLettersPrefix),
    KEEP_MODIFIER_LETTERS_PREFIX(CodePointUtils::keepModifierLettersPrefix),
    REMOVE_OTHER_LETTERS(CodePointUtils::removeOtherLetters),
    KEEP_OTHER_LETTERS(CodePointUtils::keepOtherLetters),
    REMOVE_OTHER_LETTERS_PREFIX(CodePointUtils::removeOtherLettersPrefix),
    KEEP_OTHER_LETTERS_PREFIX(CodePointUtils::keepOtherLettersPrefix),
    REMOVE_NON_SPACING_MARKS(CodePointUtils::removeNonSpacingMarks),
    KEEP_NON_SPACING_MARKS(CodePointUtils::keepNonSpacingMarks),
    REMOVE_NON_SPACING_MARKS_PREFIX(CodePointUtils::removeNonSpacingMarksPrefix),
    KEEP_NON_SPACING_MARKS_PREFIX(CodePointUtils::keepNonSpacingMarksPrefix),
    REMOVE_COMBINING_SPACING_MARKS(CodePointUtils::removeCombiningSpacingMarks),
    KEEP_COMBINING_SPACING_MARKS(CodePointUtils::keepCombiningSpacingMarks),
    REMOVE_COMBINING_SPACING_MARKS_PREFIX(CodePointUtils::removeCombiningSpacingMarksPrefix),
    KEEP_COMBINING_SPACING_MARKS_PREFIX(CodePointUtils::keepCombiningSpacingMarksPrefix),
    REMOVE_ENCLOSING_MARKS(CodePointUtils::removeEnclosingMarks),
    KEEP_ENCLOSING_MARKS(CodePointUtils::keepEnclosingMarks),
    REMOVE_ENCLOSING_MARKS_PREFIX(CodePointUtils::removeEnclosingMarksPrefix),
    KEEP_ENCLOSING_MARKS_PREFIX(CodePointUtils::keepEnclosingMarksPrefix),
    REMOVE_MARKS(CodePointUtils::removeMarks),
    KEEP_MARKS(CodePointUtils::keepMarks),
    REMOVE_MARKS_PREFIX(CodePointUtils::removeMarksPrefix),
    KEEP_MARKS_PREFIX(CodePointUtils::keepMarksPrefix),
    REMOVE_DECIMAL_DIGIT_NUMBERS(CodePointUtils::removeDecimalDigitNumbers),
    KEEP_DECIMAL_DIGIT_NUMBERS(CodePointUtils::keepDecimalDigitNumbers),
    REMOVE_DECIMAL_DIGIT_NUMBERS_PREFIX(CodePointUtils::removeDecimalDigitNumbersPrefix),
    KEEP_DECIMAL_DIGIT_NUMBERS_PREFIX(CodePointUtils::keepDecimalDigitNumbersPrefix),
    REMOVE_LETTER_NUMBERS(CodePointUtils::removeLetterNumbers),
    KEEP_LETTER_NUMBERS(CodePointUtils::keepLetterNumbers),
    REMOVE_LETTER_NUMBERS_PREFIX(CodePointUtils::removeLetterNumbersPrefix),
    KEEP_LETTER_NUMBERS_PREFIX(CodePointUtils::keepLetterNumbersPrefix),
    REMOVE_OTHER_NUMBERS(CodePointUtils::removeOtherNumbers),
    KEEP_OTHER_NUMBERS(CodePointUtils::keepOtherNumbers),
    REMOVE_OTHER_NUMBERS_PREFIX(CodePointUtils::removeOtherNumbersPrefix),
    KEEP_OTHER_NUMBERS_PREFIX(CodePointUtils::keepOtherNumbersPrefix),
    REMOVE_NUMBERS(CodePointUtils::removeNumbers),
    KEEP_NUMBERS(CodePointUtils::keepNumbers),
    REMOVE_NUMBERS_PREFIX(CodePointUtils::removeNumbersPrefix),
    KEEP_NUMBERS_PREFIX(CodePointUtils::keepNumbersPrefix),
    REMOVE_SPACE_SEPARATORS(CodePointUtils::removeSpaceSeparators),
    KEEP_SPACE_SEPARATORS(CodePointUtils::keepSpaceSeparators),
    REMOVE_SPACE_SEPARATORS_PREFIX(CodePointUtils::removeSpaceSeparatorsPrefix),
    KEEP_SPACE_SEPARATORS_PREFIX(CodePointUtils::keepSpaceSeparatorsPrefix),
    REMOVE_LINE_SEPARATORS(CodePointUtils::removeLineSeparators),
    KEEP_LINE_SEPARATORS(CodePointUtils::keepLineSeparators),
    REMOVE_LINE_SEPARATORS_PREFIX(CodePointUtils::removeLineSeparatorsPrefix),
    KEEP_LINE_SEPARATORS_PREFIX(CodePointUtils::keepLineSeparatorsPrefix),
    REMOVE_PARAGRAPH_SEPARATORS(CodePointUtils::removeParagraphSeparators),
    KEEP_PARAGRAPH_SEPARATORS(CodePointUtils::keepParagraphSeparators),
    REMOVE_PARAGRAPH_SEPARATORS_PREFIX(CodePointUtils::removeParagraphSeparatorsPrefix),
    KEEP_PARAGRAPH_SEPARATORS_PREFIX(CodePointUtils::keepParagraphSeparatorsPrefix),
    REMOVE_SEPARATORS(CodePointUtils::removeSeparators),
    KEEP_SEPARATORS(CodePointUtils::keepSeparators),
    REMOVE_SEPARATORS_PREFIX(CodePointUtils::removeSeparatorsPrefix),
    KEEP_SEPARATORS_PREFIX(CodePointUtils::keepSeparatorsPrefix),
    REMOVE_CONTROL_CATEGORY(CodePointUtils::removeControlCategory),
    KEEP_CONTROL_CATEGORY(CodePointUtils::keepControlCategory),
    REMOVE_CONTROL_CATEGORY_PREFIX(CodePointUtils::removeControlCategoryPrefix),
    KEEP_CONTROL_CATEGORY_PREFIX(CodePointUtils::keepControlCategoryPrefix),
    REMOVE_FORMAT_CATEGORY(CodePointUtils::removeFormatCategory),
    KEEP_FORMAT_CATEGORY(CodePointUtils::keepFormatCategory),
    REMOVE_FORMAT_CATEGORY_PREFIX(CodePointUtils::removeFormatCategoryPrefix),
    KEEP_FORMAT_CATEGORY_PREFIX(CodePointUtils::keepFormatCategoryPrefix),
    REMOVE_PRIVATE_USE_CATEGORY(CodePointUtils::removePrivateUseCategory),
    KEEP_PRIVATE_USE_CATEGORY(CodePointUtils::keepPrivateUseCategory),
    REMOVE_PRIVATE_USE_CATEGORY_PREFIX(CodePointUtils::removePrivateUseCategoryPrefix),
    KEEP_PRIVATE_USE_CATEGORY_PREFIX(CodePointUtils::keepPrivateUseCategoryPrefix),
    REMOVE_SURROGATE_CATEGORY(CodePointUtils::removeSurrogateCategory),
    KEEP_SURROGATE_CATEGORY(CodePointUtils::keepSurrogateCategory),
    REMOVE_SURROGATE_CATEGORY_PREFIX(CodePointUtils::removeSurrogateCategoryPrefix),
    KEEP_SURROGATE_CATEGORY_PREFIX(CodePointUtils::keepSurrogateCategoryPrefix),
    REMOVE_UNASSIGNED_CATEGORY(CodePointUtils::removeUnassignedCategory),
    KEEP_UNASSIGNED_CATEGORY(CodePointUtils::keepUnassignedCategory),
    REMOVE_UNASSIGNED_CATEGORY_PREFIX(CodePointUtils::removeUnassignedCategoryPrefix),
    KEEP_UNASSIGNED_CATEGORY_PREFIX(CodePointUtils::keepUnassignedCategoryPrefix),
    REMOVE_DASH_PUNCTUATIONS(CodePointUtils::removeDashPunctuations),
    KEEP_DASH_PUNCTUATIONS(CodePointUtils::keepDashPunctuations),
    REMOVE_DASH_PUNCTUATIONS_PREFIX(CodePointUtils::removeDashPunctuationsPrefix),
    KEEP_DASH_PUNCTUATIONS_PREFIX(CodePointUtils::keepDashPunctuationsPrefix),
    REMOVE_START_PUNCTUATIONS(CodePointUtils::removeStartPunctuations),
    KEEP_START_PUNCTUATIONS(CodePointUtils::keepStartPunctuations),
    REMOVE_START_PUNCTUATIONS_PREFIX(CodePointUtils::removeStartPunctuationsPrefix),
    KEEP_START_PUNCTUATIONS_PREFIX(CodePointUtils::keepStartPunctuationsPrefix),
    REMOVE_END_PUNCTUATIONS(CodePointUtils::removeEndPunctuations),
    KEEP_END_PUNCTUATIONS(CodePointUtils::keepEndPunctuations),
    REMOVE_END_PUNCTUATIONS_PREFIX(CodePointUtils::removeEndPunctuationsPrefix),
    KEEP_END_PUNCTUATIONS_PREFIX(CodePointUtils::keepEndPunctuationsPrefix),
    REMOVE_CONNECTOR_PUNCTUATIONS(CodePointUtils::removeConnectorPunctuations),
    KEEP_CONNECTOR_PUNCTUATIONS(CodePointUtils::keepConnectorPunctuations),
    REMOVE_CONNECTOR_PUNCTUATIONS_PREFIX(CodePointUtils::removeConnectorPunctuationsPrefix),
    KEEP_CONNECTOR_PUNCTUATIONS_PREFIX(CodePointUtils::keepConnectorPunctuationsPrefix),
    REMOVE_OTHER_PUNCTUATIONS(CodePointUtils::removeOtherPunctuations),
    KEEP_OTHER_PUNCTUATIONS(CodePointUtils::keepOtherPunctuations),
    REMOVE_OTHER_PUNCTUATIONS_PREFIX(CodePointUtils::removeOtherPunctuationsPrefix),
    KEEP_OTHER_PUNCTUATIONS_PREFIX(CodePointUtils::keepOtherPunctuationsPrefix),
    REMOVE_INITIAL_QUOTE_PUNCTUATIONS(CodePointUtils::removeInitialQuotePunctuations),
    KEEP_INITIAL_QUOTE_PUNCTUATIONS(CodePointUtils::keepInitialQuotePunctuations),
    REMOVE_INITIAL_QUOTE_PUNCTUATIONS_PREFIX(CodePointUtils::removeInitialQuotePunctuationsPrefix),
    KEEP_INITIAL_QUOTE_PUNCTUATIONS_PREFIX(CodePointUtils::keepInitialQuotePunctuationsPrefix),
    REMOVE_FINAL_QUOTE_PUNCTUATIONS(CodePointUtils::removeFinalQuotePunctuations),
    KEEP_FINAL_QUOTE_PUNCTUATIONS(CodePointUtils::keepFinalQuotePunctuations),
    REMOVE_FINAL_QUOTE_PUNCTUATIONS_PREFIX(CodePointUtils::removeFinalQuotePunctuationsPrefix),
    KEEP_FINAL_QUOTE_PUNCTUATIONS_PREFIX(CodePointUtils::keepFinalQuotePunctuationsPrefix),
    REMOVE_QUOTE_PUNCTUATIONS(CodePointUtils::removeQuotePunctuations),
    KEEP_QUOTE_PUNCTUATIONS(CodePointUtils::keepQuotePunctuations),
    REMOVE_QUOTE_PUNCTUATIONS_PREFIX(CodePointUtils::removeQuotePunctuationsPrefix),
    KEEP_QUOTE_PUNCTUATIONS_PREFIX(CodePointUtils::keepQuotePunctuationsPrefix),
    REMOVE_PUNCTUATIONS(CodePointUtils::removePunctuations),
    KEEP_PUNCTUATIONS(CodePointUtils::keepPunctuations),
    REMOVE_PUNCTUATIONS_PREFIX(CodePointUtils::removePunctuationsPrefix),
    KEEP_PUNCTUATIONS_PREFIX(CodePointUtils::keepPunctuationsPrefix),
    REMOVE_MATH_SYMBOLS(CodePointUtils::removeMathSymbols),
    KEEP_MATH_SYMBOLS(CodePointUtils::keepMathSymbols),
    REMOVE_MATH_SYMBOLS_PREFIX(CodePointUtils::removeMathSymbolsPrefix),
    KEEP_MATH_SYMBOLS_PREFIX(CodePointUtils::keepMathSymbolsPrefix),
    REMOVE_CURRENCY_SYMBOLS(CodePointUtils::removeCurrencySymbols),
    KEEP_CURRENCY_SYMBOLS(CodePointUtils::keepCurrencySymbols),
    REMOVE_CURRENCY_SYMBOLS_PREFIX(CodePointUtils::removeCurrencySymbolsPrefix),
    KEEP_CURRENCY_SYMBOLS_PREFIX(CodePointUtils::keepCurrencySymbolsPrefix),
    REMOVE_MODIFIER_SYMBOLS(CodePointUtils::removeModifierSymbols),
    KEEP_MODIFIER_SYMBOLS(CodePointUtils::keepModifierSymbols),
    REMOVE_MODIFIER_SYMBOLS_PREFIX(CodePointUtils::removeModifierSymbolsPrefix),
    KEEP_MODIFIER_SYMBOLS_PREFIX(CodePointUtils::keepModifierSymbolsPrefix),
    REMOVE_OTHER_SYMBOLS(CodePointUtils::removeOtherSymbols),
    KEEP_OTHER_SYMBOLS(CodePointUtils::keepOtherSymbols),
    REMOVE_OTHER_SYMBOLS_PREFIX(CodePointUtils::removeOtherSymbolsPrefix),
    KEEP_OTHER_SYMBOLS_PREFIX(CodePointUtils::keepOtherSymbolsPrefix),
    REMOVE_SYMBOLS(CodePointUtils::removeSymbols),
    KEEP_SYMBOLS(CodePointUtils::keepSymbols),
    REMOVE_SYMBOLS_PREFIX(CodePointUtils::removeSymbolsPrefix),
    KEEP_SYMBOLS_PREFIX(CodePointUtils::keepSymbolsPrefix);


    private final ICodePointOperation operation;

    ECodePointOperation(ICodePointOperation operation) {
        this.operation = operation;
    }

    @Override
    public void apply(CodePointBuffer buffer) {
        operation.apply(buffer);
    }
}